### ISSUE TITLE
Static view name should be prefixed

### ISSUE THREAD

**Issue by xrotwang** [sacrud/pyramid_sacrud#115]
Currently the static view for `pyramid_sacrud` has the name `static`, which may often clash with an existing configuration, resulting in a `ConfigurationConflictError`. Prefixing all names `pyramid_sacrud` places in the global configuration namespace would alleviate this problem.

**Comment by uralbash** [comment]
The name of static view for pyramid_sacrud is``admin/static/`` (with prefix ``admin``). I believe that it should't clash with other static views:

```bash
$ proutes development.ini 
Name                              Pattern                                                      View                                Method      
----                              -------                                                      ----                                ------      
__static/                         /static/*subpath                                             myapp.app:static/                   *           
__admin/static/                   /admin/static/*subpath                                       pyramid_sacrud:static/              * 
...
```
Perhaps the problem was in ``ps_alchemy`` of 0.0.1 version. Could you update ``ps_alchemy`` and try to reproduce the error.

**Comment by uralbash** [comment]
Reopen, if the problem is still there
