### ISSUE TITLE
items_per_page is hardcoded

### ISSUE THREAD

**Issue by drnextgis** [sacrud/pyramid_sacrud#120]
There is no way to set up `items_per_page` because it is hardcoded within ps_alchemy.

**Comment by uralbash** [comment]
Could you check my changes in your projects and if all is well then I'll make a new release of ``ps_alchemy``. See docs http://ps-alchemy.readthedocs.io/pages/configuration/resource.html#items-per-page

**Comment by drnextgis** [comment]
Thanks for quick fix! But I get `False` [here](https://github.com/sacrud/ps_alchemy/blob/master/ps_alchemy/resources.py#L155) and `items_per_page` settings is not applied.

**Comment by uralbash** [comment]
oops, fix it.

**Comment by drnextgis** [comment]
Now all works as expected. @uralbash coul you review my last PR for `ps_alchemy` before making a new release? https://github.com/sacrud/ps_alchemy/pull/8

**Comment by uralbash** [comment]
ok, sure
