### ISSUE TITLE
Disappearing of Enum column in update form

### ISSUE THREAD

**Issue by drnextgis** [sacrud/pyramid_sacrud#123]
One model has the following column:

```python
class_ = Column('class', Enum(*sportsman_class_types, name='sportsman_class_types'))
```

There are no problems with this column in table pyramid_sacrud mode but if open *update form* then this column disappears. Does pyramid_sacrud support `Enum` columns or anything else causes this issue?

**Comment by uralbash** [comment]
#124 same problem
