### ISSUE TITLE
Enum column should be rendered as deform SelectWidget

### ISSUE THREAD

**Issue by drnextgis** [sacrud/pyramid_sacrud#126]
Now it is simpe `<input type="text">`

**Comment by drnextgis** [comment]
I've tried to add Enum support here https://github.com/drnextgis/sacrud_deform/commit/548a6c647069ead7d9fc9963affb2511e184e393 but it doesn't work: `<select>` element appears but selected item cannot be saved. @uralbash could you take a look?

**Comment by drnextgis** [comment]
After applying last commits Enum column is displayed as SelectWidget but selected option cannot be saved.

**Comment by uralbash** [comment]
@drnextgis It happens when column name are different with attr name, I'm working on it

**Comment by uralbash** [comment]
Please, check my last commits

**Comment by drnextgis** [comment]
Now it works as expected, big thanks!
