### ISSUE TITLE
Unauthorized views / ACLs ?

### ISSUE THREAD

**Issue by olemoign** [sacrud/pyramid_sacrud#132]
When I set up Authentication / Authorization for my app, and following the documentation, http://pyramid-sacrud.readthedocs.io/pages/permissions.html , I can access the root view.

But the resources views need the PYRAMID_SACRUD_VIEW permission and I don't know where I can define the __acl__ ? The authorization lineage doesn't seem to reach my RootFactory so I cannot specify the permission there.

**Comment by uralbash** [comment]
Just add this in ``RootFactory`` or resource ``__acl__``.

```python
from pyramid_sacrud import PYRAMID_SACRUD_VIEW

...

__acl__ = [
 ...
 (Allow, Everyone, PYRAMID_SACRUD_VIEW)
]
```

If your used ``ps_alchemy`` then inherit base resource, add ``__acl__`` and pass it to config. For example:

```python
from ps_alchemy.resources import ListResource

class MyCustomResource(ListResource):
    __acl__ = [(Allow, Everyone, PYRAMID_SACRUD_VIEW), ]

settings['pyramid_sacrud.models'] = (('Group1', [MyCustomResource(Model1),
                                                 MyCustomResource(Model2)]),
                                     ('Group2', [MyCustomResource(Model3)]))

```

Also see example https://github.com/sacrud/pyramid_sacrud/blob/master/examples/auth_resource/main.py

**Comment by jcbohin** [comment]
thank you @uralbash it was indeed a ps_alchemy Resource all problem.

We tested, everything is working fine now.
